// All reads/writes of the `jobs`, `outbox_events`, and `job_attempts` tables
// go through this module -- both the API process and the worker process
// import it. Keeping it in one place is what makes the state-transition
// guards ("only move to succeeded from a non-terminal state") enforceable:
// every write path is right here.
import type { Pool, PoolClient } from "pg";
import { computeFingerprint } from "../jobs/fingerprint.js";

export type JobStatus = "queued" | "running" | "retrying" | "succeeded" | "failed";

export interface JobRow {
  id: string;
  job_type: string;
  idempotency_key: string;
  payload_fingerprint: string;
  payload: unknown;
  status: JobStatus;
  is_demo: boolean;
  attempts: number;
  max_attempts: number;
  result: unknown | null;
  error: string | null;
  created_at: Date;
  updated_at: Date;
  started_at: Date | null;
  finished_at: Date | null;
}

export interface OutboxRow {
  id: string;
  job_id: string;
  event_type: string;
  payload: { jobId: string; jobType: string; isDemo: boolean };
  published: boolean;
  publish_attempts: number;
  created_at: Date;
}

/** Thrown when an idempotency key is reused with a payload that hashes differently. */
export class IdempotencyConflictError extends Error {
  readonly name = "IdempotencyConflictError";
  constructor(
    message: string,
    public readonly existingJob: JobRow,
  ) {
    super(message);
  }
}

export interface CreateJobInput {
  /** Pre-generated by the caller (crypto.randomUUID()) so the uploaded file can be written to disk under this id *before* the DB row exists -- see api/routes/jobs.ts. */
  id: string;
  jobType: string;
  idempotencyKey: string;
  payload: unknown;
  maxAttempts: number;
  isDemo: boolean;
}

export interface CreateJobOutcome {
  job: JobRow;
  created: boolean; // false => idempotent replay of an existing job
}

/**
 * Creates the job row and its outbox event in a single transaction (the
 * "transactional outbox" pattern -- see docs/ARCHITECTURE.md). Concurrency
 * safety comes from the DB unique constraint + INSERT ... ON CONFLICT DO
 * NOTHING: exactly one of N concurrent callers with the same idempotency key
 * wins the insert; the rest fall through to the SELECT-and-compare branch.
 */
export async function createJobWithOutbox(pool: Pool, input: CreateJobInput): Promise<CreateJobOutcome> {
  const fingerprint = computeFingerprint(input.payload);
  const client = await pool.connect();
  try {
    await client.query("BEGIN");

    const insertResult = await client.query<JobRow>(
      `INSERT INTO jobs (id, job_type, idempotency_key, payload_fingerprint, payload, max_attempts, is_demo)
       VALUES ($1, $2, $3, $4, $5, $6, $7)
       ON CONFLICT (idempotency_key) DO NOTHING
       RETURNING *`,
      [input.id, input.jobType, input.idempotencyKey, fingerprint, JSON.stringify(input.payload), input.maxAttempts, input.isDemo],
    );

    if (insertResult.rows.length === 1) {
      const job = insertResult.rows[0]!;
      await client.query(
        `INSERT INTO outbox_events (job_id, event_type, payload)
         VALUES ($1, 'job.created', $2)`,
        [job.id, JSON.stringify({ jobId: job.id, jobType: job.job_type, isDemo: job.is_demo })],
      );
      await client.query("COMMIT");
      return { job, created: true };
    }

    // Conflict: a row with this idempotency key already exists. Compare
    // fingerprints to decide "same request, replay" vs "different payload, 409".
    const existing = await client.query<JobRow>("SELECT * FROM jobs WHERE idempotency_key = $1", [input.idempotencyKey]);
    await client.query("COMMIT");
    const existingJob = existing.rows[0];
    if (!existingJob) {
      // Extremely unlikely race (row deleted between conflict and select) --
      // surface as a generic error rather than a false idempotency conflict.
      throw new Error("idempotency key conflicted but existing row could not be read back");
    }
    if (existingJob.payload_fingerprint !== fingerprint) {
      throw new IdempotencyConflictError(`idempotency key "${input.idempotencyKey}" was already used with a different payload`, existingJob);
    }
    return { job: existingJob, created: false };
  } catch (err) {
    await client.query("ROLLBACK").catch(() => {});
    throw err;
  } finally {
    client.release();
  }
}

export async function getJobById(pool: Pool, id: string): Promise<JobRow | undefined> {
  const { rows } = await pool.query<JobRow>("SELECT * FROM jobs WHERE id = $1", [id]);
  return rows[0];
}

export interface ListJobsOptions {
  status?: JobStatus;
  limit: number;
  /** Opaque cursor from a previous page's `nextCursor`. */
  cursor?: string;
}

export interface ListJobsResult {
  jobs: JobRow[];
  nextCursor: string | null;
}

interface CursorPayload {
  createdAt: string;
  id: string;
}

function encodeCursor(row: JobRow): string {
  const payload: CursorPayload = { createdAt: row.created_at.toISOString(), id: row.id };
  return Buffer.from(JSON.stringify(payload), "utf8").toString("base64url");
}

function decodeCursor(cursor: string): CursorPayload {
  try {
    const parsed = JSON.parse(Buffer.from(cursor, "base64url").toString("utf8"));
    if (typeof parsed?.createdAt !== "string" || typeof parsed?.id !== "string") {
      throw new Error("malformed cursor");
    }
    return parsed;
  } catch {
    throw new Error("invalid pagination cursor");
  }
}

/** Cursor pagination ordered by (created_at DESC, id DESC), the same tie-break used to encode/decode the cursor. */
export async function listJobs(pool: Pool, options: ListJobsOptions): Promise<ListJobsResult> {
  const conditions: string[] = [];
  const params: unknown[] = [];

  if (options.status) {
    params.push(options.status);
    conditions.push(`status = $${params.length}`);
  }
  if (options.cursor) {
    const decoded = decodeCursor(options.cursor);
    params.push(decoded.createdAt, decoded.id);
    conditions.push(`(created_at, id) < ($${params.length - 1}, $${params.length})`);
  }

  const where = conditions.length > 0 ? `WHERE ${conditions.join(" AND ")}` : "";
  params.push(options.limit + 1);
  const { rows } = await pool.query<JobRow>(
    `SELECT * FROM jobs ${where} ORDER BY created_at DESC, id DESC LIMIT $${params.length}`,
    params,
  );

  const hasMore = rows.length > options.limit;
  const page = hasMore ? rows.slice(0, options.limit) : rows;
  const last = page[page.length - 1];
  return {
    jobs: page,
    nextCursor: hasMore && last ? encodeCursor(last) : null,
  };
}

// --- State transitions -------------------------------------------------
// Every UPDATE below guards its WHERE clause on the expected current
// status(es) and returns the updated row (or none). Zero rows affected means
// "someone else already moved this job past the state we expected" -- the
// caller treats that as a no-op, which is exactly what makes duplicate
// BullMQ deliveries and stale/duplicate workers safe (requirement: "protect
// terminal states from stale or duplicate workers").

export async function transitionToRunning(pool: Pool, jobId: string): Promise<JobRow | undefined> {
  // Deliberately allows re-entering 'running' from 'running' itself (not just
  // queued/retrying): after a worker crash + stalled-job recovery, BullMQ
  // redelivers the same job to a new worker while the DB may still say
  // 'running' from the dead worker's last write. Only the two terminal
  // states block this transition.
  const { rows } = await pool.query<JobRow>(
    `UPDATE jobs SET status = 'running', started_at = COALESCE(started_at, now()), updated_at = now()
     WHERE id = $1 AND status NOT IN ('succeeded', 'failed')
     RETURNING *`,
    [jobId],
  );
  return rows[0];
}

export async function transitionToRetrying(pool: Pool, jobId: string, errorMessage: string, attempts: number): Promise<JobRow | undefined> {
  const { rows } = await pool.query<JobRow>(
    `UPDATE jobs SET status = 'retrying', error = $2, attempts = $3, updated_at = now()
     WHERE id = $1 AND status = 'running'
     RETURNING *`,
    [jobId, errorMessage, attempts],
  );
  return rows[0];
}

export async function transitionToSucceeded(pool: Pool, jobId: string, result: unknown, attempts: number): Promise<JobRow | undefined> {
  const { rows } = await pool.query<JobRow>(
    `UPDATE jobs SET status = 'succeeded', result = $2, error = NULL, attempts = $3, finished_at = now(), updated_at = now()
     WHERE id = $1 AND status NOT IN ('succeeded', 'failed')
     RETURNING *`,
    [jobId, JSON.stringify(result), attempts],
  );
  return rows[0];
}

export async function transitionToFailed(pool: Pool, jobId: string, errorMessage: string, attempts: number): Promise<JobRow | undefined> {
  const { rows } = await pool.query<JobRow>(
    `UPDATE jobs SET status = 'failed', error = $2, attempts = $3, finished_at = now(), updated_at = now()
     WHERE id = $1 AND status NOT IN ('succeeded', 'failed')
     RETURNING *`,
    [jobId, errorMessage, attempts],
  );
  return rows[0];
}

// --- Attempt history -----------------------------------------------------

export async function recordAttemptStart(pool: Pool, jobId: string, attemptNumber: number, workerId: string): Promise<string> {
  const { rows } = await pool.query<{ id: string }>(
    `INSERT INTO job_attempts (job_id, attempt_number, status, worker_id)
     VALUES ($1, $2, 'running', $3)
     RETURNING id`,
    [jobId, attemptNumber, workerId],
  );
  return rows[0]!.id;
}

export async function recordAttemptEnd(pool: Pool, attemptRowId: string, status: "succeeded" | "failed" | "retrying", error: string | null): Promise<void> {
  await pool.query(
    `UPDATE job_attempts
     SET status = $2, error = $3, finished_at = now(),
         duration_ms = EXTRACT(EPOCH FROM (now() - started_at)) * 1000
     WHERE id = $1`,
    [attemptRowId, status, error],
  );
}

export async function listJobAttempts(pool: Pool, jobId: string): Promise<Array<Record<string, unknown>>> {
  const { rows } = await pool.query("SELECT * FROM job_attempts WHERE job_id = $1 ORDER BY attempt_number ASC", [jobId]);
  return rows;
}

// --- Outbox ----------------------------------------------------------------

/** Fetch and lock a batch of unpublished outbox rows using SKIP LOCKED so multiple dispatchers (if ever run) never double-claim a row. */
export async function claimUnpublishedOutboxEvents(client: PoolClient, limit: number): Promise<OutboxRow[]> {
  const { rows } = await client.query<OutboxRow>(
    `SELECT * FROM outbox_events WHERE published = false ORDER BY id ASC LIMIT $1 FOR UPDATE SKIP LOCKED`,
    [limit],
  );
  return rows;
}

export async function markOutboxPublished(client: PoolClient, id: string): Promise<void> {
  await client.query(`UPDATE outbox_events SET published = true, published_at = now() WHERE id = $1`, [id]);
}

export async function markOutboxPublishAttempt(client: PoolClient, id: string): Promise<void> {
  await client.query(`UPDATE outbox_events SET publish_attempts = publish_attempts + 1 WHERE id = $1`, [id]);
}

// --- Worker registry (heartbeats) -------------------------------------------
// Backs the frontend's worker-station display with real state: every worker
// process (main or demo) upserts its own row on startup, on every job
// pickup/completion, and on a periodic heartbeat tick. A row's *stored*
// status is only ever 'idle' or 'busy' -- 'offline' is never written by
// anyone, it is inferred by the reader from a stale last_heartbeat_at,
// because a process that has actually crashed is by definition not around
// to update its own row and say so.

export type WorkerKind = "main" | "demo";
export type StoredWorkerStatus = "idle" | "busy";

export interface WorkerRow {
  id: string;
  kind: WorkerKind;
  pid: number;
  status: StoredWorkerStatus;
  current_job_id: string | null;
  started_at: Date;
  last_heartbeat_at: Date;
}

export async function upsertWorkerHeartbeat(
  pool: Pool,
  worker: { id: string; kind: WorkerKind; pid: number; status: StoredWorkerStatus; currentJobId: string | null },
): Promise<void> {
  await pool.query(
    `INSERT INTO workers (id, kind, pid, status, current_job_id, last_heartbeat_at)
     VALUES ($1, $2, $3, $4, $5, now())
     ON CONFLICT (id) DO UPDATE
       SET status = EXCLUDED.status, current_job_id = EXCLUDED.current_job_id, last_heartbeat_at = now()`,
    [worker.id, worker.kind, worker.pid, worker.status, worker.currentJobId],
  );
}

export async function listWorkers(pool: Pool): Promise<WorkerRow[]> {
  const { rows } = await pool.query<WorkerRow>("SELECT * FROM workers ORDER BY kind, started_at ASC");
  return rows;
}

export async function deleteWorker(pool: Pool, id: string): Promise<void> {
  await pool.query("DELETE FROM workers WHERE id = $1", [id]);
}

/** Prunes worker rows whose heartbeat has been stale for a long time -- covers a worker that was force-killed (Task Manager, `docker kill`, a Windows Stop-Process) and so never ran its own graceful-shutdown cleanup. Called periodically by cleanup/retention.ts. */
export async function deleteLongStaleWorkers(pool: Pool, olderThanMs: number): Promise<number> {
  const { rowCount } = await pool.query("DELETE FROM workers WHERE last_heartbeat_at < now() - ($1 || ' milliseconds')::interval", [olderThanMs]);
  return rowCount ?? 0;
}

/** Used once at API startup to clear out stale demo-worker rows left over from a previous run (the API re-spawns a fresh demo pool every time it starts). */
export async function deleteWorkersByKind(pool: Pool, kind: WorkerKind): Promise<void> {
  await pool.query("DELETE FROM workers WHERE kind = $1", [kind]);
}

// --- Retention -------------------------------------------------------------

/** Terminal jobs finished before `cutoff` whose files haven't been purged yet. See cleanup/retention.ts. */
export async function findJobsNeedingRetentionSweep(pool: Pool, cutoff: Date, limit: number): Promise<Pick<JobRow, "id">[]> {
  const { rows } = await pool.query<Pick<JobRow, "id">>(
    `SELECT id FROM jobs
     WHERE files_purged_at IS NULL AND finished_at IS NOT NULL AND finished_at < $1
     ORDER BY finished_at ASC LIMIT $2`,
    [cutoff, limit],
  );
  return rows;
}

export async function markFilesPurged(pool: Pool, jobId: string): Promise<void> {
  await pool.query("UPDATE jobs SET files_purged_at = now() WHERE id = $1", [jobId]);
}
